const PDFDocument = require('pdfkit');

function fmtMoney(n) {
  const v = Number(n) || 0;
  return `RM ${v.toFixed(2)}`;
}

/** Generate a simple payslip PDF buffer from payslip data object. */
function generatePayslipPdfBuffer(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('Staff Hub — Payslip', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#555555').text(data.periodLabel || '', { align: 'center' });
    doc.moveDown(1.5);
    doc.fillColor('#000000');

    doc.fontSize(12).text(`Employee: ${data.name || ''} (${data.staffId || ''})`);
    if (data.department) doc.text(`Department: ${data.department}`);
    if (data.position) doc.text(`Position: ${data.position}`);
    if (data.email) doc.text(`Email: ${data.email}`);
    doc.moveDown(1);

    const att = data.attendance || {};
    doc.fontSize(13).text('Attendance', { underline: true });
    doc.fontSize(11).text(`Days with complete clock: ${att.daysWithCompleteClock ?? 0}`);
    doc.text(`Total hours worked: ${att.totalHoursWorked ?? 0}`);
    doc.moveDown(1);

    doc.fontSize(13).text('Earnings', { underline: true });
    const earnings = data.earnings || {};
    doc.fontSize(11).text(`${earnings.label || 'Gross salary'}: ${fmtMoney(earnings.grossSalary)}`);
    doc.moveDown(0.5);

    doc.fontSize(13).text('Deductions', { underline: true });
    const deductions = data.deductions || [];
    if (deductions.length === 0) {
      doc.fontSize(11).text('—');
    } else {
      deductions.forEach((d) => {
        doc.fontSize(11).text(`${d.label}: ${fmtMoney(d.amount)}`);
      });
    }
    doc.moveDown(1);

    doc.fontSize(14).text(`Net pay: ${fmtMoney(data.netPay)}`, { align: 'right' });

    if (data.adminRemarks) {
      doc.moveDown(1);
      doc.fontSize(11).fillColor('#333333').text(`HR notes: ${data.adminRemarks}`);
    }

    if (data.disclaimer) {
      doc.moveDown(1.5);
      doc.fontSize(9).fillColor('#666666').text(data.disclaimer, { align: 'left' });
    }

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999999').text(
      `Generated by Staff Hub on ${new Date().toISOString().slice(0, 10)}`,
      { align: 'center' },
    );

    doc.end();
  });
}

function bufferToPdfDataUrl(buffer) {
  return `data:application/pdf;base64,${buffer.toString('base64')}`;
}

module.exports = { generatePayslipPdfBuffer, bufferToPdfDataUrl };
